// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"a-block-that-holds-blocks": 16.9,
	"what-the-loop-knows": 9.1,
	"one-at-a-time": 16.3,
	"the-results-come-out": 11.7,
	"swap-the-container": 14.5,
	"all-at-once": 12.5,
	"two-schedules-one-shape": 7.8,
};
