// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"a-run-happens": 14.8,
	"the-record": 11.1,
	"what-it-really-did": 17.1,
	"read-it-backwards": 24.5,
	"every-run-writes-one": 9.2,
};
