// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-queue": 15.4,
	"the-responder": 24.5,
	"alert-in": 15.4,
	"reading-the-signals": 22,
	"creating-the-records": 23.6,
	"the-queue-drains": 19.4,
	"morning": 15,
};
