// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"a-fork-in-the-flow": 10.8,
	"the-rule-decides": 16.2,
	"the-other-path": 15,
	"swap-the-decider": 13.7,
	"the-model-decides": 12.6,
	"the-run-record": 11.5,
	"still-one-workflow": 8.4,
};
