// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"a-normal-workflow": 10.3,
	"add-the-agent": 7.7,
	"inside-the-agent": 24.5,
	"the-run-record": 9.1,
	"whats-ahead": 14.8,
	"still-a-workflow": 8.4,
};
