// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-board": 14,
	"the-desk-takes-shape": 16.2,
	"wired-by-reference": 10.6,
	"armed": 6.2,
	"the-pull": 11.3,
	"the-fan": 14.4,
	"one-analyst": 19,
	"the-signals": 15,
	"the-desk-at-rest": 13.7,
};
