// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-empty-table": 12.8,
	"the-machine": 24.5,
	"wired-by-reference": 11.5,
	"the-fan": 17.6,
	"one-lane-one-lead": 22.8,
	"the-scramble-finish": 15.7,
	"the-write-back": 23.6,
	"the-sent-campaign": 18.1,
};
