// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-backlog": 10.9,
	"the-fleet-takes-shape": 18.8,
	"wired-by-reference": 12,
	"lights-out": 8.4,
	"midnight": 13.3,
	"the-fan": 14.7,
	"one-engineer": 22.8,
	"the-wall": 15.5,
	"morning": 11.1,
};
