// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-workflow": 9.1,
	"the-run-fires": 7.5,
	"calls-connect": 12.1,
	"one-conversation": 13.8,
	"three-at-once": 16.2,
	"outcomes-land": 12.3,
	"the-campaign-ran": 11.3,
};
