// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"one-surface": 19.6,
	"two-kinds": 18.3,
	"wired-together": 22.1,
	"the-series": 19.3,
	"into-the-workflow": 18.5,
};
