// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"a-tool-in-action": 12.6,
	"the-schema": 15.8,
	"the-code": 17.1,
	"onto-the-table": 8,
	"the-agent-decides": 12.5,
};
