// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-table": 14.9,
	"rows-and-fields": 10.4,
	"the-workflow": 11,
	"the-read": 11.1,
	"the-write": 12.8,
	"the-record": 9.8,
	"queue-and-record": 16.2,
};
