// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-task": 8.7,
	"the-toolbelt": 11,
	"the-run-begins": 13.6,
	"reading-the-pages": 9,
	"hands-on-the-web": 20.3,
	"the-brief-comes-back": 9,
	"the-evidence-trail": 10.8,
};
