// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-board": 16.1,
	"the-desk-takes-shape": 21.9,
	"wired-by-reference": 11.5,
	"the-sweep": 9.4,
	"the-research-fan": 15,
	"one-market": 14.1,
	"the-board-lights-up": 17.1,
	"the-desk": 14.4,
};
