// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"the-workflow-you-know": 8.6,
	"it-becomes-a-block": 15.7,
	"the-call-begins": 8.9,
	"inside-the-call": 18.6,
	"back-with-the-result": 10.6,
	"workflows-all-the-way-up": 13,
};
