// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"answer-from-docs": 11.7,
	"the-knowledge-base": 16.1,
	"split-into-passages": 17.6,
	"the-closest-passages": 11,
	"into-the-context": 18.1,
	"the-search-record": 16.3,
	"still-your-documents": 8.8,
};
