// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"an-agent-you-built": 9,
	"deploy-as-a-tool": 12.3,
	"a-stranger-calls": 11.6,
	"the-rush": 17.2,
	"you-call-theirs": 13.3,
	"the-agent-economy": 14.9,
};
