// GENERATED by scripts/vo-sync.ts — do not edit by hand.
// Scene durations re-timed to the narration in narration-v1.md
// (max(authored visual minimum, audio + 0.7s pad)). Re-run vo-sync
// after massaging narration; delete this file's entries to revert to
// authored timing.
export const VO_TIMING: Record<string, number> = {
	"one-box": 12.8,
	"members-join": 12.6,
	"the-boundary": 13.1,
	"connect-an-account": 13.2,
	"one-credential-three-blocks": 19.3,
	"the-unit": 9.8,
};
